version: '3'

services:

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'

  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction
    ports:
      - "8001:5432"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql


  worker:
    build: worker
    volumes:
      - ./worker:/app
      - ./db:/app/db
    environment:
      - PYTHONUNBUFFERED=1

  server:
    build: server
    volumes:
      - ./server:/server
      - ./db:/server/db
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1